name: statsig
description: Statsig SDK for Dart. Statsig enables developers to ship code faster and more safely.
version: 0.5.0
homepage: https://statsig.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  crypto: ^3.0.1
  http: ^0.13.4
  meta: ^1.7.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  mockito: ^5.1.0
  build_runner: ^2.1.7
  nock: 1.1.3
